### ISSUE TITLE
Debug build of model viewer doesn't work on Windows 7

### ISSUE THREAD

**Issue by nasenbaer43** [walbourn/directxtkmodelviewer#2]
Hi Chuck,
guess this method is not available for Windows 7. E.g. see https://msdn.microsoft.com/en-us/library/windows/desktop/dn268307(v=vs.85).aspx: Minimum supported client: Windows 8.1 [desktop apps \| Windows Store apps].
Removing the #if defined(_DEBUG) stuff works.

**Comment by walbourn** [comment]
Fixed in [this commit](https://github.com/walbourn/directxtkmodelviewer/commit/1c4974b84e6466cdabf600433427c59984eed58d)
