### ISSUE TITLE
application crashed when loading D3D11 sample's .sdkmesh

### ISSUE THREAD

**Issue by StanwieCB** [walbourn/directxtkmodelviewer#3]
I was trying to view the raw geometry of D3D11's MultithreadedRendering11 sample by loading 

`DirectXSamples\MultithreadedRendering11\Media\SquidRoom\SquidRoom.sdkmesh`

and the model viewer crashed.

I've also tried some other sample's .sdkmesh file and it threw errors as well.

So does it mean that the model view only supports single-mesh .sdkmesh file?

Many thanks!

**Comment by walbourn** [comment]
If you run the Debug build, you'll see the following output:

    D3D11 ERROR: ID3D11Device::CreateInputLayout: The provided input signature expects to read an element with SemanticName/Index: 'NORMAL'/0, but the declaration doesn't provide a matching name. [ STATE_CREATION ERROR #163: CREATEINPUTLAYOUT_MISSINGELEMENT]

So the basic issue is that the legacy ``SDKMESH`` model doesn't contain per-vertex normals. The DirectX Tool Kit requires per-vertex normals for basically any lighting support.

**Comment by walbourn** [comment]
If you do make this hack assumption, it still fails to load looking for a non-existent DDS file 'default' names that was put in there by an older exporter:

* default.dds
* default-normalmap.dds

If you provide some kind of files for those, it will load.

**Comment by walbourn** [comment]
Try out the latest [release](https://github.com/walbourn/directxtkmodelviewer/releases). You'll still need to provide some kind of ``default.dds`` and ``default-normalmap.dds`` for that model.
